### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by msurguy** [blackketter/Switch#3]
Hi! It would be nice to have the long press time to be optionally set by the user to something other than the default 300ms and perhaps even allow for multiple stages of long - press event. 

For example in some applications pressing the button for 5 seconds activates one mode, pressing for 15 seconds - another mode, etc.

**Comment by blackketter** [comment]
The long press delay can be set in the constructor:

`Switch(byte _pin, byte PinMode=INPUT_PULLUP, bool polarity=LOW, int debounceDelay=50, int longPressDelay=400, int doubleClickDelay=250);`

But it's reasonable to have a setter so that this value could be adjusted after construction, possibly to allow chaining of long press events for multiple modes as you describe.

**Comment by msurguy** [comment]
@blackketter thank you for the explanation! Sorry I didn't reply to you in time!
